### ISSUE TITLE
Why do you need to customize these tables? Are the official three tables not enough?

### ISSUE THREAD

**Issue by wxq851685279** [Basit-Mahmood/spring-authorization-server-spring-boot-3#1]
`create table oauth2_client (
    id bigint auto_increment not null PRIMARY KEY,
    client_id varchar(200) not null,
    client_id_issued_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_name varchar(200) not null,
	client_secret varchar(200) not null,
	client_secret_expires_at timestamp DEFAULT NULL,
    authentication_method varchar(100) not null,
	authorization_grant_type varchar(100) not null,
	scopes varchar(1000) not null,
	redirect_uris varchar(1000),
	registered boolean NOT null default 0,
	created_date timestamp NOT null,
  	created_by BIGINT default 0 NOT null,
  	updated_date timestamp,
  	updated_by BIGINT,
  	deleted_date timestamp,
  	constraint UC_oauth2_client_id_client_id UNIQUE (id, client_id),
	constraint UC_oauth2_client_client_id UNIQUE (client_id)
);

create table oauth2_client_token_setting (
  	id bigint auto_increment not null primary key,
	client_id varchar(200) not null,
  	access_token_time integer not null,
	access_token_time_unit varchar(50) not null,
	refresh_token_time integer NOT NULL,
	refresh_token_time_unit varchar(50) not null,
	created_date timestamp NOT null,
  	created_by BIGINT default 0 NOT null,
  	updated_date timestamp,
  	updated_by BIGINT,
  	deleted_date timestamp,
  	constraint FK_oauth2_client_token_setting_client_id foreign key (client_id) 
	references oauth2_client (client_id) on delete cascade
);

create table oauth2_client_setting (
  	id bigint auto_increment not null primary key,
	client_id varchar(200) not null,
  	require_authorization_consent boolean null,
  	created_date timestamp NOT null,
  	created_by BIGINT default 0 NOT null,
  	updated_date timestamp,
  	updated_by BIGINT,
  	deleted_date timestamp,
  	constraint FK_oauth2_client_setting_client_id foreign key (client_id) 
	references oauth2_client (client_id) on delete cascade
);

`

**Comment by Basit-Mahmood** [comment]
@wxq851685279 I didn't customized any tables. In fact I use the existing tables present in the internal library of spring. Why I made these tables ? It's just one approach of doing it. When I was using in-memory code for loading oauth2 client in my spring boot 2 repository. I was using the same thing. I have clients, token setting and client settings. So just to make it align I used this approach. Spring tables are fine but for token and client settings they use json instead of simple varchar or integer type. 

I though it is simple to use 1 hour or 1 day for token settings instead of using json. 

I can make a single table in which I could put all the information in the form of josn for token settings and client settings. But as
spring are using different POJO for these token settings and client settings that is why I made tables in this way. Also I use simple type like integer or varchar.

Also there are more settings for token and clients. If anyone want to use these settings. Any one can simply add columns for those settings and there is just one class that would need to be change.

But as I said it's just a sample. If you don't like it you can directly use spring tables. Instead of making different tables and load clients from these tables and then converted it to spring registered clients. You can directly insert clients in the spring tables. But as I said these tables use json instead of simple varchar or integer types so you have to be careful. One small mistake in josn can cause database error.

So just to make it simple I made these tables. But there is no special reason. 

Hopefully you got your answer now. 

Thanks & Regards
Basit Mahmood Ahmed

**Comment by wxq851685279** [comment]
Got it, thanks
